### PR TITLE
Go bindings for libvmdk.

### PR DESCRIPTION
**Pull request by rosmo**
These are simple Go bindings for libvmdk created with Swig and some C++ glue. 

The test suite requires a simple pre-built VMDK test file (128 KB), not sure if you want to include that in the repository or not? Let me know if I should add it to the PR.

### CODE REVIEW

**Comment by joachimmetz** [comment]
Thanks for the contributions. I'll have to think before I integrate these changes. I was planning a more native go-binding at some point, not using SWIG. Also this introduces a C++ dependency as well.

**Comment by joachimmetz** [comment]
Regarding testdata, I'm storing it in https://github.com/libyal/testdata

**Comment by rosmo** [comment]
Thanks for considering. I think getting a nicer "native" Go-binding without using C++ and Swig is hard. You'd have to either re-implement the library in Go or create a wrapper using Cgo. My PR doesn't add any new builds/requirements to the library, it's only relevant if one wants to use Go.

**Comment by joachimmetz** [comment]
> My PR doesn't add any new builds/requirements to the library, it's only relevant if one wants to use Go.

is adds a dependency on swig and a C++ compiler. Using C++ also means that now the binding has to deal with the both C (malloc/free) and C++ (new/delete) memory allocation. 

Where cgo (C.malloc/C.free) seems to be a wrapper around C (malloc/free), also see: https://golang.org/cmd/cgo/

Some more things to consider before going the cgo route https://www.cockroachlabs.com/blog/the-cost-and-complexity-of-cgo/. Sounds like a native go implementation might be the better route to go (pun intended).

**Comment by joachimmetz** [comment]
I'll close this issue, seeing end result is that the proposed changes complicate maintenance.

**Pull request closed without merging**
