### PR TITLE
Add nuget targets file.

### PR DESCRIPTION
**Pull request by APriestman**
Change nuget paths to prevent warning.

### CODE REVIEW

**Comment by APriestman** [comment]
Having the .targets file allows easier integration into Visual Studio - it sets up the include/library folders and copies the dlls.

Switching from "lib" to "build" for the base folder seems more consistent with other packages I've seen, and having it as "lib" was generating a warning when I ran nuget pack.

**Comment by joachimmetz** [comment]
FYI the libvmdk.nuspec file is generated by https://github.com/libyal/libyal/blob/master/scripts/source-generate.py. Any documentation on these changes and the target file format?

**Comment by APriestman** [comment]
Looking at it further, it seems like the .targets file does need to be in a build folder, but a lib folder also makes sense. Let me see if it works to only put the .targets file in build and leave the lib folder as-is.

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package

**Comment by joachimmetz** [comment]
ack, let me know how that turns out. I recall the lib folder was the advise/default for an earlier version of nuget creation tools. I've not followed this space too much.

**Pull request closed without merging**
